name: Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  coverage:
    runs-on: ubuntu-24.04
    env:
      COV_MIN: 100

    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: ${{ github.token }}

      - name: Node Setup
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Dependencies
        run: npm ci

      - name: Coverage Report
        run: npm run cover:report

      - name: Coverage Extraction
        id: extract_coverage
        run: |
          COVERAGE=$(
          node -e "
          const fs = require('fs');
          const { extractCoverage } = require('@nicolawealth/code_coverage_extractor');
          const coverageData = JSON.parse(fs.readFileSync('./coverage/coverage-final.json', 'utf-8'))
          const result = extractCoverage(coverageData, './codecov/badge.json');
          console.log(result);
          ")
          COVERAGE=$(echo $COVERAGE | xargs)
          INT_COV=${COVERAGE%.*}
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
          echo "INT_COV=$INT_COV" >> $GITHUB_ENV

      - name: Coverage Threshold Assertion
        run: |
          if [ "$INT_COV" -lt "$COV_MIN" ]; then
            echo "Assertion failed: Coverage is $INT_COV% (required: $COV_MIN%)"
            exit 1
          else
            echo "Assertion passed: Coverage is $INT_COV%"
          fi

      - name: Badge Update
        if: github.event_name == 'push'
        run: |
          git config --global user.email "software@nicolawealth.com"
          git config --global user.name "actlion"
          git remote set-url origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
          if ! git diff --quiet codecov/badge.json; then
            git add codecov/badge.json
            git commit -m "Update coverage badge"
            git push origin main
          fi

