name: Publish
on:
  release:
    types: [ created ]

permissions:
  id-token: write
  contents: read

jobs:
  npm:
    name: NPM
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Node Setup
        uses: actions/setup-node@v6
        with:
          node-version: '22.17.1'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish
